services:
  its-certcenter:
    image: 192.168.100.63:5000/its-certcenter:1.0.0
    container_name: its-certcenter
    ports:
    - "9250:9250"
    environment:
    - ACME_ACCOUNT=itsower567@gmail.com
    - ACME_DNS_API=https://auth.acme-dns.io/register
    volumes:
    - C:/Users/Administrator/Volumes/its-certcenter/storage:/its-certcenter
